# Generated by Django 4.2 on 2023-10-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
